### ISSUE TITLE
bug？？？？

### ISSUE THREAD

**Issue by hahahawu** [Jack-Q/reg2dfa#1]
when the reg is 1*(0|111*)*1*,the minimal deteministic finite automaton seems to be incorrect.

**Comment by Jack-Q** [comment]
Thanks a lot for testing and your feedback. However, I couldn't find where the bug is. May I request a counter-example that matches the regular expression `1*(0|111*)1`while fails to fit the min-DFA?

![min](https://cloud.githubusercontent.com/assets/9014072/24838845/a04b9672-1d82-11e7-8a86-6adb74acef56.png)

**Comment by hahahawu** [comment]
I am embarrassed that I typed an inappropriate reg in last issue. I could have submitted that when the reg is `1*(0|111*)*1*` ,the minimal dfa is incorrect. However, when I tested again this morning, the answer was correct. Have you fixed bug?

**Comment by Jack-Q** [comment]
There were some bugs when convert regular expression with continous `*`'s to NFA. The following commits are addressed on this problem: 36f81b2f4fa3a23419f2be4e291960974a0f0c0e and f9550430328a012ce2f05c43a450b1349b056025 . Thanks again for your feedback!

**Comment by Jack-Q** [comment]
There were some bugs when convert regular expression with continous `*`'s to NFA. The following commits are addressed on this problem: 36f81b2f4fa3a23419f2be4e291960974a0f0c0e and f9550430328a012ce2f05c43a450b1349b056025 . Thanks again for your feedback!
